DATASET:
  TRAIN:
    NAME: blenderdata
    PARAMS:
      split: train
      sampling_ratio: 1
      crop_height: 720
      crop_width: 1280
      randomverticalflip: False
      event_cfg:
        NAME: sbn
        PARAMS:
          num_of_event: 5000000
          stack_method: MixedDensityEventStacking
          stack_size: 10
          use_preprocessed_image: False
  VALID:
    NAME: blenderdata
    PARAMS:
      split: trainval
      sampling_ratio: 1
      crop_height: 720
      crop_width: 1280
      randomverticalflip: False
      event_cfg:
        NAME: sbn
        PARAMS:
          num_of_event: 5000000
          stack_method: MixedDensityEventStacking
          stack_size: 10
          use_preprocessed_image: False
DATALOADER:
  TRAIN:
    NAME: get_multi_epochs_dataloader
    PARAMS:
      batch_size: 4
      shuffle: True
      drop_last: True
  VALID:
    NAME: get_multi_epochs_dataloader
    PARAMS:
      batch_size: 4
      shuffle: True
      drop_last: True
  TEST:
    NAME: get_multi_epochs_dataloader
    PARAMS:
      batch_size: 4
      shuffle: False
      drop_last: False