TOTAL_EPOCH: 300
METHOD: base
DATASET:
  TRAIN:
    NAME: blenderdata
    PARAMS:
      split: train
      sampling_ratio: 1
      crop_height: 768
      crop_width: 1344
      randomhorizontalflip: False
      event_cfg:
        NAME: sbn
        PARAMS:
          num_of_event: 1000000
          stack_method: MixedDensityEventStacking
          stack_size: 10
          use_preprocessed_image: False
  VALID:
    NAME: blenderdata
    PARAMS:
      split: valid
      sampling_ratio: 1
      crop_height: 768
      crop_width: 1344
      randomhorizontalflip: False
      event_cfg:
        NAME: sbn
        PARAMS:
          num_of_event: 1000000
          stack_method: MixedDensityEventStacking
          stack_size: 10
          use_preprocessed_image: False
DATALOADER:
  TRAIN:
    NAME: get_multi_epochs_dataloader
    PARAMS:
      batch_size: 1
      shuffle: False
      drop_last: True
  VALID:
    NAME: get_multi_epochs_dataloader
    PARAMS:
      batch_size: 1
      shuffle: False
      drop_last: True
  TEST:
    NAME: get_multi_epochs_dataloader
    PARAMS:
      batch_size: 2
      shuffle: False
      drop_last: False
MODEL:
  NAME: EventStereoObjectDetectionNetwork
  PARAMS:
    concentration_net_cfg:
      PARAMS:
        in_channels: 10
        attention_method: soft
        base_channels: 32
    feature_extraction_net_cfg:
      PARAMS:
        backbone:
          type: ResNeXt
          depth: 101
          groups: 64
          base_width: 4
          num_stages: 4
          out_indices: [0, 1, 2, 3]
          frozen_stages: 1
          norm_cfg:
            type: BN
            requires_grad: True
          style: pytorch
          init_cfg:
              type: Pretrained
              checkpoint: 'open-mmlab://resnext101_64x4d'
        neck:
          type: FPN
          in_channels: [256, 512, 1024, 2048]
          out_channels: 256
          num_outs: 5
    disp_head_cfg:
      is_freeze: True
      PARAMS:
        in_channels: 1
        max_disp: 288
        refine_channels: 1
    object_detection_head_cfg:
      PARAMS:
        num_channels_input_feature: 256
        min_bbox_size: 5
        # detection
        num_classes: 1
        in_channels: 256
        feat_channels: 256
        num_stacked_convs: 2
        num_topk_candidates: 1000
        bbox_expand_factor: 1.6
        strides: [8, 16, 32]
        norm_cfg:
          type: BN
          momentum: 0.03
          eps: 0.001
        act_cfg:
          type: ReLU
        # region proposal
        nms_pre: 3000
        # right bbox regression
        right_roi_feat_size: 7
        iou_threshold: 0.4
        candidates_k: 8
        # keypt prediction
        keypts_feat_size: 14
    losses_cfg:
      objdet_loss_cfg:
        NAME: ObjdetLoss
      disp_loss_cfg:
        NAME: DisparityLoss
        ls_loss_weight: 1.0
        warp_loss_weight: 100.0
        use_warp_loss: False
OPTIMIZER:
  NAME: Adam
  PARAMS:
    lr: 0.0005
    weight_decay: 0.0001
SCHEDULER:
  NAME: CosineAnnealingWarmupRestarts
  PARAMS:
    cycle_mult: 1.0
    first_cycle_steps: 100
    gamma: 1.0
    lr_ratio: 0.0001
    warmup_steps: 3
