TOTAL_EPOCH: 300
METHOD: base
DATASET:
  TRAIN:
    NAME: facets
    PARAMS:
      split: train
      sampling_ratio: 1
      crop_height: 480
      crop_width: 672
      randomhorizontalflip: False
      isLoadCOCOFormat: True
      event_cfg:
        NAME: sbn
        PARAMS:
          num_of_event: 500000
          stack_method: MixedDensityEventStacking
          stack_size: 10
          use_preprocessed_image: False
  VALID:
    NAME: facets
    PARAMS:
      split: valid
      sampling_ratio: 1
      crop_height: 480
      crop_width: 672
      randomhorizontalflip: False
      isLoadCOCOFormat: True
      event_cfg:
        NAME: sbn
        PARAMS:
          num_of_event: 500000
          stack_method: MixedDensityEventStacking
          stack_size: 10
          use_preprocessed_image: False
  TEST:
    NAME: facets
    PARAMS:
      split: test
      sampling_ratio: 1
      crop_height: 480
      crop_width: 672
      randomhorizontalflip: False
      isLoadCOCOFormat: True
      event_cfg:
        NAME: sbn
        PARAMS:
          num_of_event: 500000
          stack_method: MixedDensityEventStacking
          stack_size: 10
          use_preprocessed_image: False
DATALOADER:
  TRAIN:
    NAME: get_multi_epochs_dataloader
    PARAMS:
      batch_size: 1
      shuffle: False
      drop_last: True
  VALID:
    NAME: get_multi_epochs_dataloader
    PARAMS:
      batch_size: 1
      shuffle: False
      drop_last: True
  TEST:
    NAME: get_sequence_dataloader
    PARAMS:
      batch_size: 1
      shuffle: False
      drop_last: False
MODEL:
  NAME: EventStereoObjectDetectionNetwork
  PARAMS:
    concentration_net_cfg:
      PARAMS:
        in_channels: 10
        attention_method: soft
        base_channels: 32
    feature_extraction_net_cfg:
      PARAMS:
        backbone:
          type: CSPDarknet
          deepen_factor: 0.33
          widen_factor: 0.5
          out_indices: [2, 3, 4]
          use_depthwise: False
          spp_kernal_sizes: [5, 9, 13]
          norm_cfg:
            type: 'BN'
            momentum: 0.03
            eps: 0.001
          act_cfg:
            type: 'Swish'
        neck:
          type: YOLOXPAFPN
          in_channels: [128, 256, 512]
          out_channels: 128
          num_csp_blocks: 1
          use_depthwise: False
          upsample_cfg: 
            scale_factor: 2
            mode: nearest
          norm_cfg:
            type: 'BN'
            momentum: 0.03
            eps: 0.001
          act_cfg:
            type: 'Swish'
    disp_head_cfg:
      is_freeze: True
      PARAMS:
        in_channels: 1
        max_disp: 168
        refine_channels: 1
    object_detection_head_cfg:
      PARAMS:
        freeze_leftobjdet: True
        min_bbox_size: 5
        # detection
        num_classes: 4
        in_channels: 128
        feat_channels: 256
        num_stacked_convs: 2
        num_topk_candidates: 30
        bbox_expand_factor: 1.0
        strides: [8, 16, 32]
        norm_cfg:
          type: BN
          momentum: 0.03
          eps: 0.001
        act_cfg:
          type: ReLU
        # region proposal
        nms_pre: 100
        nms_iou_threshold: 0.5
        # right bbox regression
        right_roi_feat_size: 7
        r_iou_threshold: 0.4
        candidates_k: 8
        keypt_pred_cfg:
          is_enable: False
          PARAMS:
            # keypt prediction
            keypts_feat_size: 14
            keypt_in_channels: 3
            keypt_feat_channels: 512
            is_train_keypt: False
        facet_pred_cfg:
          is_enable: True
          PARAMS:
            enlarge_roi_factor: 2.0
            facet_feat_size: 14
            facet_in_channels: 3
            facet_feat_channels: 512
            is_train_facet: True
        # inference params
        lconfidence_threshold: 0.15
        rscore_threshold: 0.9
        final_iou_threshold: 0.05
    losses_cfg:
      objdet_loss_cfg:
        NAME: ObjdetLoss
      disp_loss_cfg:
        NAME: DisparityLoss
        ls_loss_weight: 1.0
        warp_loss_weight: 100.0
        use_warp_loss: False
OPTIMIZER:
  NAME: Adam
  PARAMS:
    lr: 0.0005
    weight_decay: 0.0001
  KEYPT_PARAMS:
    lr: 0.0005
    weight_decay: 0.0001
SCHEDULER:
  NAME: CosineAnnealingWarmupRestarts
  PARAMS:
    cycle_mult: 1.0
    first_cycle_steps: 100
    gamma: 1.0
    lr_ratio: 0.0001
    warmup_steps: 3
