TOTAL_EPOCH: 1
METHOD: base
DATASET:
  TRAIN:
    NAME: eventpicking
    PARAMS:
      split: train
      sampling_ratio: 1
      crop_height: 480
      crop_width: 640
      randomhorizontalflip: False
      event_cfg:
        NAME: sbn
        PARAMS:
          num_of_event: 100000
          stack_method: MixedDensityEventStacking
          stack_size: 10
          # tau: 20000  # 50ms
          use_preprocessed_image: False
  VALID:
    NAME: eventpicking
    PARAMS:
      split: valid
      sampling_ratio: 1
      crop_height: 480
      crop_width: 640
      randomhorizontalflip: False
      event_cfg:
        NAME: sbn
        PARAMS:
          num_of_event: 100000
          stack_method: MixedDensityEventStacking
          stack_size: 10
          # tau: 20000  # 50ms
          use_preprocessed_image: False
  TEST:
    NAME: eventpicking
    PARAMS:
      split: test
      sampling_ratio: 1
      crop_height: 480
      crop_width: 640
      randomhorizontalflip: False
      event_cfg:
        NAME: sbn
        PARAMS:
          num_of_event: 100000
          stack_method: MixedDensityEventStacking
          stack_size: 10
          # tau: 20000  # 50ms
          use_preprocessed_image: False
DATALOADER:
  TRAIN:
    NAME: get_multi_epochs_dataloader
    PARAMS:
      batch_size: 1
      shuffle: False
      drop_last: True
  VALID:
    NAME: get_multi_epochs_dataloader
    PARAMS:
      batch_size: 1
      shuffle: False
      drop_last: True
  TEST:
    NAME: get_multi_epochs_dataloader
    PARAMS:
      batch_size: 1
      shuffle: False
      drop_last: False
MODEL:
  NAME: EventStereoMatchingNetwork
  PARAMS:
    concentration_net:
      PARAMS:
        in_channels: 10
        attention_method: soft
        base_channels: 32
    disparity_estimator:
      PARAMS:
        in_channels: 1
        max_disp: 192
        refine_channels: 1
